####Імпорти

In [132]:
import numpy as np

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [133]:
#1.1 визначаємо функцію
def sigmoid (z):
    sig = 1 / (1 + np.exp(-z))
    return sig


In [134]:
#1.2
z = [-2, -1, 0, 1, 2]
sigmoids = []
for x in z:
    sig = sigmoid(x)
    sigmoids.append(sig)
print(f'Сігмоїди:', sigmoids)


Сігмоїди: [0.11920292202211755, 0.2689414213699951, 0.5, 0.7310585786300049, 0.8807970779778823]




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [135]:
# функція гіпотези для логістичної регресії
def hypothesis (theta, X):
    z = np.dot(X, theta)
    hyp = sigmoid(z)
    return hyp

In [136]:
#змінні
theta = np.array([0.5, -0.5])
X = np.array([[1, 2],
              [1, -1],
              [1, 0],
              [1, 1]])

In [137]:
hypothesis (theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [138]:
#змінна y
y = np.array([1, 0, 1, 0])

In [139]:
#функція підрахунку градієнтів функції втрат

def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)
    gradient = (1/m) * np.dot(X.T,(h-y))

    return gradient

In [140]:
gradient = compute_gradient(theta, X, y)
print("Градієнти:", gradient)

Градієнти: [ 0.05776464 -0.36899431]



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [141]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.zeros(X.shape[1])
    m = len(y)
    errors = []

    for _ in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta = theta - lr * gradient
        h = hypothesis(theta, X)
        loss = (-1/m) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
        errors.append(loss)

    return theta, errors

In [142]:
theta, errors = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)
print("Оптимальні значення theta:", theta)


Оптимальні значення theta: [-0.2893693   0.77655125]


#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

5.1

In [145]:
def predict_proba(theta, X):
    p_p = hypothesis (theta, X)

    return p_p

In [159]:
p_p = predict_proba(theta, X)
p_p

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

5.2

In [149]:
def predict(theta, X, threshold=0.5):
    p_p = hypothesis (theta, X)
    predict = []

    for p in (p_p):
        if p >= threshold:
            a = 1
        else:
            a = 0
        predict.append(a)
        predict_np = np.array(predict)
    return predict_np

In [152]:
predict_np = predict(theta, X, threshold=0.5)
predict_np

array([1, 0, 0, 1])

5.3

In [153]:
#змінні
y_true = y
y_pred = predict_np

In [157]:
def accuracy(y_true, y_pred):
    m = len (y_true)
    acc = (np.sum((y_true == y_pred).astype(int)))/m

    return acc

In [158]:
acc = accuracy(y_true, y_pred)
acc

0.5

5.4  Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [161]:
print (f'Використовую модель з Тета  {theta}')
print (f'Mоделлю передбачено наступні імовірності належності кожного з екземплярів в матриці X до класу 1:', p_p )
print (f'Передбачено наступні класи кожного екземпляра з матриці X:', predict_np )
print (f'Точність моделі:', acc )

Використовую модель з Тета  [-0.2893693   0.77655125]:
Mоделлю передбачено наступні імовірності належності кожного з екземплярів в матриці X до класу 1: [0.77966809 0.25617965 0.42815828 0.61944235]
Передбачено наступні класи кожного екземпляра з матриці X: [1 0 0 1]
Точність моделі: 0.5
