##Імпорт бібліотек

In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [40]:
#Створення вектора
vector = np.random.rand(10)
print('Вектор vector:')
print(vector)
print("\nРозмір вектора vector:")
print(vector.shape)

Вектор vector:
[0.72213099 0.6775464  0.0870962  0.03892277 0.62641281 0.31145092
 0.48105008 0.41403498 0.8171242  0.39581789]

Розмір вектора vector:
(10,)


In [12]:
#Create matrix
matrix =  np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])
print('Матриця matrix:')
print(matrix)
print("\nРозмір матриці matrix:")
print(matrix.shape)

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці matrix:
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [41]:
#Завдання 2.1
vector_sum_const =np.round(np.add(vector, 10), 2)
print('Вектор vector_sum_const:')
print(vector_sum_const)

Вектор vector_sum_const:
[10.72 10.68 10.09 10.04 10.63 10.31 10.48 10.41 10.82 10.4 ]


In [17]:
#Завдання 2.2
mutrix_mult_const = 2 * matrix
print('Матриця mutrix_mult_const:')
print(mutrix_mult_const)

Матриця mutrix_mult_const:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [42]:
#Завдання 2.3
vector_sq = np.square(vector)
print('Вектор vector_sq:')
print(vector_sq)

Вектор vector_sq:
[0.52147317 0.45906912 0.00758575 0.00151498 0.39239301 0.09700167
 0.23140918 0.17142496 0.66769196 0.1566718 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [29]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [30]:
#Завдання 3.1
result_matrix = np.dot(A.T, B.T)

print(result_matrix)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [31]:
#Завдання 3.2
#Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на вектор C і який результат буде: буде результат 2 х 1

result_mult_v = np.dot(result_matrix, C)
print('Матриця result_mult_v:')
print(result_mult_v)


Матриця result_mult_v:
[[0.2034]
 [0.2846]]


In [32]:
#Завдання 3.3
#Вважаю, що результат буде 2 х 2
result_mult_D = np.dot(result_matrix, D)
print('Матриця result_mult_D:')
print(result_mult_D)

Матриця result_mult_D:
[[0.2034 0.7281]
 [0.2846 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [34]:
#1
result_matrix_T = result_matrix.T

In [43]:
#2
vector_T = vector.T
print(f'Форма попередньої структури:', vector.shape)
print(f'Форма нової структури:', vector_T.shape)

Форма попередньої структури: (10,)
Форма нової структури: (10,)


Після транспонування форма структури не змінилася

In [45]:
#3
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
print(f'Форма нової структури:', column_vector.shape)

[[0.72213099]
 [0.6775464 ]
 [0.0870962 ]
 [0.03892277]
 [0.62641281]
 [0.31145092]
 [0.48105008]
 [0.41403498]
 [0.8171242 ]
 [0.39581789]]
Форма нової структури: (10, 1)


За результатами  операції numpy.expand_dims, змінилася форма структури - додався вимір і ветор став колонкою

In [46]:
#4
column_vector_T = column_vector.T
print(column_vector_T)
print(f'Форма нової структури:', column_vector_T.shape)

[[0.72213099 0.6775464  0.0870962  0.03892277 0.62641281 0.31145092
  0.48105008 0.41403498 0.8171242  0.39581789]]
Форма нової структури: (1, 10)
